### ISSUE TITLE
Wrong scripts uploaded

### ISSUE THREAD

**Issue by Geetima2021** [nikhil5-b/VSD-5-DAYS-TCL-SCRIPTING-WORKSHOP#1]
The uploaded scripts does not generate the same logo as shown in the repository. Also check the typo in your UI. The alignment of text is also not proper.

![issue1](https://github.com/nikhil5-b/VSD-5-DAYS-TCL-SCRIPTING-WORKSHOP/assets/63381455/3a013872-7ac1-46ef-a78a-b2c6e2d39176)

**Comment by nikhil5-b** [comment]
ok.yes that's true.Sorry in rush hour i was forgeted the command and all
the tcl file to upload and update.
Extremely sorry for my mistake. Sorry for inconvenience.
I will update my file right now.Please cross verify my uploaded files on
github.
