### ISSUE TITLE
TCL script related

### ISSUE THREAD

**Issue by Geetima2021** [nikhil5-b/VSD-5-DAYS-TCL-SCRIPTING-WORKSHOP#3]
Please upload the scripts which gives the output as shown in the report. The uploaded scripts is errorneous. What is the usage of cd command in your script?

![image](https://github.com/nikhil5-b/VSD-5-DAYS-TCL-SCRIPTING-WORKSHOP/assets/63381455/3b12fe32-509c-49a0-bddd-014e6ebb83c4)

**Comment by nikhil5-b** [comment]
Please kindly go through the repository I just uploaded to my running tcl
file. line number 17 for the working directory.
again sorry for the inconvenience caused due to unaligned code.
