### ISSUE TITLE
Variable related issue

### ISSUE THREAD

**Issue by Geetima2021** [nikhil5-b/VSD-5-DAYS-TCL-SCRIPTING-WORKSHOP#4]
Please check if you have some issues in typo of your variables in your script.

![nissue1](https://github.com/nikhil5-b/VSD-5-DAYS-TCL-SCRIPTING-WORKSHOP/assets/63381455/3b7e7822-cbd9-4c1a-9df9-87f0a9257ca6)

**Comment by nikhil5-b** [comment]
corrected.please kindly find out the repo.
